#pragma once
// -----------------------------------------------------------------------------
// This file is GENERATED by CMake. Do not edit by hand.
// Path (build tree): <build>/generated/aether/config_build.hpp
// -----------------------------------------------------------------------------

// Project version
#define AETHER_VERSION_MAJOR @AETHER_VERSION_MAJOR@
#define AETHER_VERSION_MINOR @AETHER_VERSION_MINOR@
#define AETHER_VERSION_PATCH @AETHER_VERSION_PATCH@

// Spatial dimension
#define AETHER_DIM @AETHER_DIM@
#define AETHER_PHYSICS_STR "@AETHER_PHYSICS@"
#define AETHER_PHYSICS_KIND @AETHER_PHYSICS_KIND@  // 1=Euler, 2=SRHD, 3=MHD

#define AETHER_PHYSICS_EULER @AETHER_PHYSICS_EULER_INT@
#define AETHER_PHYSICS_MHD   @AETHER_PHYSICS_MHD_INT@
#define AETHER_PHYSICS_SRHD  @AETHER_PHYSICS_SRHD_INT@


// Backend features (0 or 1)
#define AETHER_ENABLE_OPENMP @AETHER_ENABLE_OPENMP_INT@
#define AETHER_ENABLE_MPI    @AETHER_ENABLE_MPI_INT@
#define AETHER_ENABLE_CUDA   @AETHER_ENABLE_CUDA_INT@

#define AETHER_BOUNDS_CHECK @AETHER_BOUNDS_CHECK_INT@
